groups:
- name: custom_rules
  rules:
    - record: node_memory_MemFree_in_percent
      expr: 100-(100*node_memory_MemFree_bytes/node_memory_MemTotal_bytes)
- name: alert_rules
  rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels: 
        severity: critical
      annotations:
        summary: "Instance [{{ $labels.instance}}] is Down"
        description: "[{{ $labels.instance}}] of job [{{ $labels.job}}] is down for more than a minute"